# Data Cleaning

In [33]:
import pandas as pd
from pathlib import Path

# Set project root directory (one level above the notebook folder)
BASE_DIR = Path().resolve().parent

# Read the data file
file_path = BASE_DIR / "data/raw/stzh.zwn_meldungen_p.csv"
reports = pd.read_csv(file_path)

# Date transformation
reports["requested_datetime"] = pd.to_datetime(reports["requested_datetime"])

# Data from the last 10 years
ten_years_ago = pd.Timestamp.now() - pd.DateOffset(years=10)
reports = reports[reports["requested_datetime"] > ten_years_ago]

# Date column
reports["date"] = reports["requested_datetime"].dt.date

# Extract useful columns
print(reports.columns)
reports = reports[["date","service_code", "e", "n", "geometry"]]

display(reports.sort_values(by="date", ascending=False).head())
display(reports.sort_values(by="date", ascending=True).head())

Index(['objectid', 'service_request_id', 'requested_datetime',
       'agency_sent_datetime', 'updated_datetime', 'e', 'n', 'service_code',
       'service_name', 'status', 'userid', 'title', 'detail', 'media_url',
       'interface_used', 'service_notice', 'description', 'url', 'geometry',
       'date'],
      dtype='object')

,date,service_code,e,n,geometry
72186,2026-04-16,Abfall/Sammelstelle,2680495,1248455,POINT (2680495 1248455)
72182,2026-04-16,Allgemein,2681516,1246219,POINT (2681516 1246219)
72177,2026-04-16,Abfall/Sammelstelle,2685747,1246246,POINT (2685747 1246246)
72178,2026-04-16,Abfall/Sammelstelle,2682307,1249366,POINT (2682307 1249366)
72179,2026-04-16,Abfall/Sammelstelle,2679762,1251038,POINT (2679762 1251038)

,date,service_code,e,n,geometry
7484,2016-04-17,Abfall/Sammelstelle,2684171,1246733,POINT (2684171 1246733)
7237,2016-04-17,Beleuchtung/Uhren,2683289,1248057,POINT (2683289 1248057)
7485,2016-04-18,Grünflächen/Spielplätze,2682712,1247955,POINT (2682712 1247955)
7488,2016-04-18,Abfall/Sammelstelle,2681880,1248999,POINT (2681880 1248999)
7270,2016-04-18,Strasse/Trottoir/Platz,2682229,1245442,POINT (2682229 1245442)